version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "27017:27017"
    volumes:
      - mongodata1:/data/db

  # mongo1:
  #   image: mongo:latest
  #   ports:
  #     - "27011:27017"
  #   command: --replSet my-mongo-set --keyFile /etc/mongo/mongo-keyfile
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #   volumes:
  #     - mongodata1:/data/db
  #     - /home/jefer/dev/benchmarks/databases/python/conf/mongo/key:/etc/mongo/mongo-keyfile:ro

  # mongo2:
  #   image: mongo:latest
  #   ports:
  #     - "27012:27017"
  #   command: --replSet my-mongo-set --keyFile /etc/mongo/mongo-keyfile
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #   volumes:
  #     - mongodata2:/data/db
  #     - /home/jefer/dev/benchmarks/databases/python/conf/mongo/key:/etc/mongo/mongo-keyfile:ro

  # mongo3:
  #   image: mongo:latest
  #   ports:
  #     - "27013:27017"
  #   command: --replSet my-mongo-set --keyFile /etc/mongo/mongo-keyfile
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #   volumes:
  #     - mongodata3:/data/db
  #     - /home/jefer/dev/benchmarks/databases/python/conf/mongo/key:/etc/mongo/mongo-keyfile:ro

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    command:
      - "--smp 20"
      - "--memory 10G"
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
    volumes:
      - cassandra-data:/var/lib/cassandra
      - ./conf/cassandra/cassandra.yaml:/etc/cassandra/cassandra.yaml
      # - /home/jefer/dev/benchmarks/databases/python/conf/cassandra/cassandra.yaml:/etc/cassandra/cassandra.yaml

  # cassandra2:
  #   image: cassandra:latest
  #   ports:
  #     - "9043:9042"
  #   command:
  #     - "--smp 20"
  #     - "--memory 10G"
  #   environment:
  #     - CASSANDRA_SEEDS=cassandra
  #     - CASSANDRA_CLUSTER_NAME=TestCluster
  #     - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
  #     - CASSANDRA_DC=datacenter1
  #     - CASSANDRA_RACK=rack1
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "500m"
  #   volumes:
  #     - cassandra-data2:/var/lib/cassandra
  #     - ./conf/cassandra/cassandra.yaml:/etc/cassandra/cassandra.yaml

  # cassandra3:
  #   image: cassandra:latest
  #   ports:
  #     - "9044:9042"
  #   command:
  #     - "--smp 20"
  #     - "--memory 10G"
  #   environment:
  #     - CASSANDRA_SEEDS=cassandra
  #     - CASSANDRA_CLUSTER_NAME=TestCluster
  #     - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
  #     - CASSANDRA_DC=datacenter1
  #     - CASSANDRA_RACK=rack1
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "500m"
  #   volumes:
  #     - cassandra-data3:/var/lib/cassandra
  #     - ./conf/cassandra/cassandra.yaml:/etc/cassandra/cassandra.yaml

  scylla:
    image: scylladb/scylla:latest
    container_name: scylla
    ports:
      - "19042:9042"
      # - "19160:9160"
      # - "19180:9180"
      - "10010:10000"
    volumes:
      - scylla_data:/var/lib/scylla
    command:
      - "--smp 7"
      - "--memory 4G"
    environment:
      - SCYLLA_ARGS=--developer-mode=1
      - SCYLLA_IO_SETUP=1
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
    networks:
      scylla:

  
  # scylla2:
  #   image: scylladb/scylla:latest
  #   ports:
  #     - "19043:9042"
  #     # - "19160:9160"
  #     # - "19180:9180"
  #     - "10011:10000"
  #   volumes:
  #     - scylla_data2:/var/lib/scylla
  #   command:
  #     - "--smp 7"
  #     - "--memory 4G"
  #     - "--seeds=scylla"
  #   environment:
  #     - SCYLLA_ARGS=--developer-mode=1
  #     - SCYLLA_IO_SETUP=1
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "500m"
  #   networks:
  #     scylla:

  # scylla3:
  #   image: scylladb/scylla:latest
  #   ports:
  #     - "19044:9042"
  #     # - "19160:9160"
  #     # - "19180:9180"
  #     - "10012:10000"
  #   volumes:
  #     - scylla_data3:/var/lib/scylla
  #   command:
  #     - "--smp 6"
  #     - "--memory 4G"
  #     - "--seeds=scylla"
  #   environment:
  #     - SCYLLA_ARGS=--developer-mode=1
  #     - SCYLLA_IO_SETUP=1
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "500m"
  #   networks:
  #     scylla:

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: postgres
      MYSQL_USER: postgres
      MYSQL_PASSWORD: example

  mariadb:
    image: mariadb:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: postgres
      MYSQL_USER: postgres
      MYSQL_PASSWORD: example

  # neo4j:
  #   image: neo4j:latest
  #   ports:
  #     - "7474:7474"
  #     - "7687:7687"
  #   environment:
  #     NEO4J_AUTH: neo4j/example

  # arangodb:
  #   image: arangodb/arangodb:latest
  #   ports:
  #     - "8529:8529"
  #   environment:
  #     ARANGO_ROOT_PASSWORD: example

  hbase:
    image: dajobe/hbase
    container_name: hbase-docker
    ports:
      - "16000:16000"   # Master RPC port
      - "16010:16010"   # Master Web UI
      - "16020:16020"   # RegionServer RPC port
      - "16030:16030"   # RegionServer Web UI
      - "2181:2181"     # ZooKeeper client port
      - "9090:9090"
    environment:
      - HBASE_MANAGES_ZK=true

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./conf/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9091:9090'

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana

  cadvisor:
    image: google/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - '8080:8080'

  couchbase:
    image: couchbase:latest
    ports:
      - "8091-8094:8091-8094"
      - "11210:11210"
    environment:
      - COUCHBASE_SERVER_MEMORY_QUOTA=512
      - COUCHBASE_CLUSTER_RAMSIZE=512
      - COUCHBASE_CLUSTER_NAME=my-cluster
      - COUCHBASE_CLUSTER_USERNAME=admin
      - COUCHBASE_CLUSTER_PASSWORD=password
      - COUCHBASE_BUCKET=default
      - COUCHBASE_BUCKET_TYPE=couchbase
      - COUCHBASE_BUCKET_RAMSIZE=128
      - COUCHBASE_RBAC_USERNAME=myuser
      - COUCHBASE_RBAC_PASSWORD=mypassword
      - COUCHBASE_RBAC_ROLE=bucket_full_access[*]
    volumes:
      - couchbase-data:/opt/couchbase/var

  couchdb:
    image: couchdb:latest
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    volumes:
      - couchdb-data:/opt/couchdb/data



volumes:
  mongodata1:
  mongodata2:
  mongodata3:
  scylla_data:
  scylla_data2:
  scylla_data3:
  cassandra-data:
  cassandra-data2:
  cassandra-data3:
  grafana_data:
  couchbase-data:
  couchdb-data:

networks:
  scylla:
    driver: bridge